### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by BobbyTowers** [thebigsmileXD/JumpPadsPE#2]
Could you update this to the latest version of PM?

**Comment by inxomnyaa** [comment]
Interesting. This plugin is 4 years old and has not been touched since 3 years (only added readme back then) ^^"
I will give it a try

**Comment by BobbyTowers** [comment]
THANK YOU! WORKS FINE!

**Comment by inxomnyaa** [comment]
I might upload a patch soon, i noticed some weird issues when looking up/down, it does not launch far

**Comment by BobbyTowers** [comment]
You have to look where you want to go. As in if you look down, you jump down.

**Comment by BobbyTowers** [comment]
Sorry for this but could you update this? 
[AfkKick.zip](https://github.com/thebigsmileXD/JumpPadsPE/files/4584536/AfkKick.zip)

**Comment by inxomnyaa** [comment]
https://poggit.pmmp.io/ci/thebigsmileXD/JumpPadsPE/JumpPadsPE/dev:6
